export const DEFAULT_STATE = {
  articles: [],
  article: {},
  article_comments: [],
  albums: [],
  albums_user: [],
  todos_user: [],
  photos: [],
  utilisateurs: {},
  id: "",
  title: "",
  body: "",
  userId: "",
  searchTerm: "",
  notifications: [],
  isLoading: false,
 }
